### ISSUE TITLE
GPU device conflict

### ISSUE THREAD

**Issue by genekogan** [Mayukhdeb/eden-clip#4]
When using `CUDA_VISIBLE_DEVICES` flag to hard-limit eden-clip to a subset of GPUs, the following stack trace occurs *after* the first `img=generate` completes and before it goes to the next resolution. guessing it's a discrepancy with which GPUs GPUUtil thinks are available. 

rather than debugging this, i'm guessing a better solution would be to just implement GPU device index limiting directly into eden, as GPUUtil allows this.

```
99%|#########9| 99/100 [00:21<00:00,  4.61it/s]
100%|##########| 100/100 [00:21<00:00,  4.62it/s]
100%|##########| 100/100 [00:21<00:00,  4.65it/s]
[2021-07-15 14:44:57,319: WARNING/MainProcess] 

[2021-07-15 14:44:57,347: WARNING/MainProcess] Traceback (most recent call last):

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "eden_server.py", line 91, in run
    img = generate(config_octave, perceptor = perceptor, preprocess = preprocess, model = model, device = config['__gpu__'], img = img, progress = progress, progress_step_size = progress_step_size)

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "/home/abraham/dev/eden-clip/core/generate.py", line 51, in generate
    lats = Pars(img, config, model, device = device).to(device)

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "/home/abraham/dev/eden-clip/core/pars.py", line 24, in __init__
    z, _, [_, _, indices] = model.encode(img)

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/ml4a/models/submodules/taming-transformers/taming/models/vqgan.py", line 52, in encode
    h = self.encoder(x)

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/ml4a/models/submodules/taming-transformers/taming/modules/diffusionmodules/model.py", line 413, in forward
    hs = [self.conv_in(x)]

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)

[2021-07-15 14:44:57,347: WARNING/MainProcess] RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)

[2021-07-15 14:44:57,347: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:


[2021-07-15 14:44:57,347: WARNING/MainProcess] Traceback (most recent call last):

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "/home/abraham/dev/eden/eden/hosting.py", line 73, in run
    output = block.__run__(args)

[2021-07-15 14:44:57,347: WARNING/MainProcess]   File "eden_server.py", line 114, in run
    raise Exception(str(e))

[2021-07-15 14:44:57,347: WARNING/MainProcess] Exception: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 1 does not equal 0 (while checking arguments for cudnn_convolution)
```

**Comment by genekogan** [comment]
instead of using `CUDA_VISIBLE_DEVICES` I used the excludeID flag in eden to limit the GPUs, but I'm still getting the same error.

```
100%|##########| 100/100 [00:20<00:00,  4.94it/s]
100%|##########| 100/100 [00:20<00:00,  4.95it/s]
[2021-07-15 14:55:12,653: WARNING/MainProcess] 

[2021-07-15 14:55:12,680: WARNING/MainProcess] Traceback (most recent call last):

[2021-07-15 14:55:12,680: WARNING/MainProcess]   File "eden_server.py", line 91, in run
    img = generate(config_octave, perceptor = perceptor, preprocess = preprocess, model = model, device = config['__gpu__'], img = img, progress = progress, progress_step_size = progress_step_size)

[2021-07-15 14:55:12,680: WARNING/MainProcess]   File "/home/abraham/dev/eden-clip/core/generate.py", line 51, in generate
    lats = Pars(img, config, model, device = device).to(device)

[2021-07-15 14:55:12,680: WARNING/MainProcess]   File "/home/abraham/dev/eden-clip/core/pars.py", line 24, in __init__
    z, _, [_, _, indices] = model.encode(img)

[2021-07-15 14:55:12,680: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/ml4a/models/submodules/taming-transformers/taming/models/vqgan.py", line 52, in encode
    h = self.encoder(x)

[2021-07-15 14:55:12,680: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)

[2021-07-15 14:55:12,680: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/ml4a/models/submodules/taming-transformers/taming/modules/diffusionmodules/model.py", line 413, in forward
    hs = [self.conv_in(x)]

[2021-07-15 14:55:12,680: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)

[2021-07-15 14:55:12,680: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 423, in forward
    return self._conv_forward(input, self.weight)

[2021-07-15 14:55:12,680: WARNING/MainProcess]   File "/home/abraham/.local/share/virtualenvs/dev-uLiuCJPC/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 420, in _conv_forward
    self.padding, self.dilation, self.groups)

[2021-07-15 14:55:12,680: WARNING/MainProcess] RuntimeError: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 2 does not equal 0 (while checking arguments for cudnn_convolution)

[2021-07-15 14:55:12,680: WARNING/MainProcess] 
During handling of the above exception, another exception occurred:


[2021-07-15 14:55:12,681: WARNING/MainProcess] Traceback (most recent call last):

[2021-07-15 14:55:12,681: WARNING/MainProcess]   File "/home/abraham/dev/eden/eden/hosting.py", line 73, in run
    output = block.__run__(args)

[2021-07-15 14:55:12,681: WARNING/MainProcess]   File "eden_server.py", line 114, in run
    raise Exception(str(e))

[2021-07-15 14:55:12,681: WARNING/MainProcess] Exception: Expected tensor for argument #1 'input' to have the same device as tensor for argument #2 'weight'; but device 2 does not equal 0 (while checking arguments for cudnn_convolution)

[2021-07-15 14:55:12,683: INFO/MainProcess] Task run[d532a8e2-e5ee-4788-86b1-bf47e77bd222] succeeded in 28.967287765000947s: {'ERROR': 'Expected tensor for argument #1 \'input\' to have the same device as tensor for argument #2 \'weight\'; but device 2 does not equal 0 (while checking arguments for cudnn_convolution). Check Host\'s logs for full traceback'}
```

**Comment by genekogan** [comment]
Actually, I am finding I am getting this error even without limiting GPUs through GPUUtil or CUDA_VISIBLE_DEVICES. doesn't happen on the original instance on abraham.ai, just on the test site. possibly something from latest eden commit? The gist of it is that `taming` is expecting something to come in on GPU 0, regardless of what the config says, but only on the second round (it does everything at 128pixels to completion, and then fails). continuing to investigate further.

**Comment by Mayukhdeb** [comment]
I think this is more likely to be an issue on eden-clip rather than eden. Because as long as the user is using `x = x.to(device)` where `device = config['__gpu__']`,  and not something less desirable like `x.cuda()`, which defaults to `"cuda:0"`.

**Comment by genekogan** [comment]
I think we've removed all instances of `x.cuda()` and replaced them with explicit device. The problem might even be further, like in `taming_transformers`. still i'm unclear why it's not occuring in our other instance of eden-clip.

**Comment by Mayukhdeb** [comment]
> The problem might even be further, like in `taming_transformers`

This is what I suspect it to be, for now. Need to investigate the original repo itself.

**Comment by genekogan** [comment]
this is now fixed!
